version: '2'
services:
    quizapplication-app:
        image: quizapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://quizapplication-mysql:3306/quizapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    quizapplication-mysql:
        extends:
            file: mysql.yml
            service: quizapplication-mysql
